apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Admin role - full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, certificates, *, *, allow

    # DevOps role - deployment focused
    p, role:devops, applications, *, */*, allow
    p, role:devops, repositories, *, *, allow
    p, role:devops, clusters, get, *, allow

    # Developer role - limited access
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, clusters, get, *, allow

    # Security team role - audit access
    p, role:security, applications, get, */*, allow
    p, role:security, repositories, get, *, allow
    p, role:security, accounts, get, *, allow
    p, role:security, clusters, get, *, allow

    # Readonly role - view only (default)
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, clusters, get, *, allow

    # Built-in admin user assignment
    g, admin, role:admin

    # Group assignments (for future SSO integration)
    g, devops-team, role:devops
    g, developers, role:developer
    g, security-team, role:security

  scopes: '[groups]'
