apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  argocd.token: |
    # This should be an ArgoCD API token
    # For demo purposes, we'll configure it to use internal service
